### ISSUE TITLE
Loose File Loading ignores EN/BASE folders

### ISSUE THREAD

**Issue by IBNobody** [Raytwo/p5rcbt#1]
I noticed that the loose file loading wouldn't load files located in an `sd:/p5r/EN` or `sd:/p5r/BASE` folders. If this is by design, it might be worth noting in the readme.

```
Filepath: sd:/p5r/BUTTON/BUTTON_NX.PAK
Filepath: app0:/CPK/BIND/BUTTON/BUTTON_NX.PAK
Filepath: PATCH1/BUTTON/BUTTON_NX.PAK
Filepath: EN/BUTTON/BUTTON_NX.PAK
Filepath: BUTTON/BUTTON_NX.PAK
```

So, for example, if I wanted to override `BUTTON/BUTTON_NX.PAK` and the mod I want to use has it stored in `BASE/BUTTON/BUTTON_NX.PAK`, I have to move the `BUTTON` folder out of the `sd:/p5r/BASE` folder.

**Comment by Raytwo** [comment]
It is not really "by design" but just "how it works" in CriWare. 
I have also added directories with example in the release archive which should've made it clear.

I will consider adding a note anyways

**Comment by IBNobody** [comment]
A note in the `readme.md` is all that is needed, then. Something like...

"Remove any parent `BASE`/`EN`/`PATCH1` folders from mods, if present."

Just as some background to help explain how I got here: As a new user to Skyline and CriWare, I didn't know to omit the base/en folders. Adding to the confusion, the other guides that use `CpkFileBuilder.exe` to build a PATCH1 file give instructions to put the whole folder structure in there.
