### ISSUE TITLE
P5R CBT Breaks on the Latest Update for Royal

### ISSUE THREAD

**Issue by MewtwoFanz** [Raytwo/p5rcbt#2]
When I try to use this with the latest Update (1.0.2), It crashes before the game even loads saying "The software closed because an error occurred."

**Comment by RhanCandia** [comment]
> When I try to use this with the latest Update (1.0.2), It crashes before the game even loads saying "The software closed because an error occurred."

I am encountering the same issue. Did you ever manage to make it work?

**Comment by RhanCandia** [comment]
@Raytwo I tried to get the updated subsdk9 from https://github.com/skyline-dev/skyline and replaced the one in the releases package of this mod but still didn't work.

What needs to be patched in the game's main.ndpm file? Is there a guide somewhere?

**Comment by fnr1r** [comment]
I uninstalled the update and it seems to work again.

I think the update changed the offsets at which these functions have to be patched in (the ones in `src/lib.rs`).

NOTE: If you want to build this project, you should install `cargo-skyline` as per <https://crates.io/crates/skyline>.
